---
title: "memory_based_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


# Memory-based Collaborative Filtering Algorithm Starter Code


## Building the UI matrix for the MS Data 

```{r}
setwd("E:/GitHub/project-3-algorithms-project-3-algorithms-group-3")
source("E:/GitHub/project-3-algorithms-project-3-algorithms-group-3/lib/functions.R")
```

```{r}
setwd("E:/GitHub/project-3-algorithms-project-3-algorithms-group-3/data/MS_sample")

# Load the data
MS_train <- read.csv("data_train.csv", as.is = TRUE, header = TRUE)
MS_train <- MS_train[, 2:4]
```

```{r}
head(MS_train)
```

```{r}
# Transform from narrow to wide, i.e. user-item matrix 
# using MS_data_transform function

# Below takes 2.17 minutes
MS_UI <- MS_data_transform(MS_train)
save(MS_UI, file = "MS_UI.RData")
```

```{r}
dim(MS_UI)
MS_UI[1:10,1:10]
```

```{r}
# Matrix Calculations
visit_nums <- rowSums(MS_UI != 0)

table(visit_nums)
mean(visit_nums)
median(visit_nums)
```

```{r}
# Looping instead of rowSums()

long.row.sums <- function(UI) {
  vec <- rep(NA, nrow(UI))
  for (i in 1:nrow(UI)) {
    vec[i] <- sum(UI[i,], na.rm = TRUE)
  }
  return(vec)
}

system.time(long.row.sums(MS_UI))
system.time(rowSums(MS_UI, na.rm = TRUE))
```

```{r}
vec <- long.row.sums(MS_UI)
all(vec == rowSums(MS_UI, na.rm = TRUE))
```


## Building the UI matrix for the EachMovie Data

```{r}
setwd("E:/GitHub/project-3-algorithms-project-3-algorithms-group-3/data/eachmovie_sample")

# Load the data
movie_train <- read.csv("data_train.csv", as.is = TRUE, header = TRUE)
movie_train <- movie_train[, 2:4]
```

```{r}
head(movie_train)
```

```{r}
# How we might fill in the user-item matrix using %in%

# Find sorted lists of users and vroots
users  <- sort(unique(movie_train$User))
movies <- sort(unique(movie_train$Movie))
```

```{r}
length(users)
length(movies)
```

```{r}
# Initiate the UI matrix
UI            <- matrix(NA, nrow = length(users), ncol = length(movies))
row.names(UI) <- users
colnames(UI)  <- movies
```

```{r}
# We consider just user 1, finding user 1's movies and ratings
movies  <- movie_train$Movie[movie_train$User == users[1]]
ratings <- movie_train$Score[movie_train$User == users[1]]

ord     <- order(movies)
movies  <- movies[ord]
ratings <- ratings[ord]

system.time(UI[1, colnames(UI) %in% movies] <- ratings)
```

```{r}
# How we might fill in the user-item matrix using loops 

long.in <- function(movies, ratings) {
  
  # Cycle through the ratings, find the corresponding column
  for (i in 1:length(ratings)) {
    column <- which(colnames(UI) == movies[i])
    UI[2, column] <- ratings[i]
    print(column)
  }
  
}

system.time(long.in(movies, ratings))
  
all(UI[1, ] == UI[2,], na.rm = TRUE)
```

```{r}
# Compute the full matrix
# Below takes about 4 minutes

movie_UI <- movie_data_transform(movie_train)
save(movie_UI, file = "movie_UI.RData")
```

```{r}
movie_UI[1:10,1:10]
```

```{r}
# Some calculations
total_ratings <- rowSums(movie_UI, na.rm = TRUE)

table(total_ratings)
mean(total_ratings)
median(total_ratings)
```


## Calculating the Similarity Weights of the Users

```{r}
# Initiate the similarity weight matrix

movie_UI         <- as.matrix(movie_UI)
movie_sim_weight <- matrix(NA, nrow = nrow(movie_UI), ncol = nrow(movie_UI)) # it's a square
```

```{r}
# Can calculate Pearson correlation between two rows of UI matrix as:

rowA <- movie_UI[1, ]
rowB <- movie_UI[2, ]

cor(rowA, rowB, method = 'pearson', use = "pairwise.complete.obs")
```

```{r}
# Another way:

joint_values <- !is.na(rowA) & !is.na(rowB)
cor(rowA[joint_values], rowB[joint_values], method = 'pearson')
```

```{r}
# First fill in row 1 of the similarity matrix using apply

system.time(vec1 <- apply(movie_UI, 1, cor, movie_UI[1, ], method = 'pearson', use = "pairwise.complete.obs"))
```

```{r}
# Now fill in row 1 of the similarity matrix looping over the columns and 
# calculating pairwise correlations

long.way <- function(row.num) {
  
  for(i in 1:nrow(movie_UI)) {
    movie_sim_weight[row.num, i] <- cor(movie_UI[i, ], movie_UI[row.num, ], method = 'pearson', use = "pairwise.complete.obs")
  }
  
}

system.time(long.way(1))
```

### Pearson correlation similarity

```{r}
# Calculate the full weights on the movie data
# The below took 87 minutes on my Macbook, 35 on my iMac

movie_sim_pearson <- calc_weight(movie_UI,method=="pearson")
save(movie_sim_pearson, file = "movie_sim_pearson.RData")
```

```{r}
movie_sim_pearson[1:10,1:10]
```

```{r}
# Calculate the full weights on the MS data
# The below took 30 minutes on my Macbook and 14 on my iMac

MS_sim_pearson <- calc_weight(MS_UI,method=="pearson")
save(MS_sim_pearson, file = "MS_sim_pearson.RData")
```

```{r}
MS_sim_pearson[1:10,1:10]
```

### Spearman correlation similarity

```{r}
movie_sim_spearman <- calc_weight(movie_UI,method="spearman")
save(movie_sim_spearman, file = "movie_sim_spearman.RData")
```

```{r}
movie_sim_spearman[1:10,1:10]
```

```{r}
MS_sim_spearman <- calc_weight(MS_UI,method="spearman")
save(MS_sim_spearman, file = "MS_sim_spearman.RData")
```

```{r}
MS_sim_spearman[1:10,1:10]
```

### Mean Squared Difference Similarity

```{r}
movie_sim_msd <- calc_weight(movie_UI,method="mean_squared_diff")
save(movie_sim_msd, file = "movie_sim_msd.RData")
```

```{r}
movie_sim_msd[1:10,1:10]
```

```{r}
MS_sim_msd <- calc_weight(MS_UI,method="mean_squared_diff")
save(MS_sim_msd, file = "MS_sim_msd.RData")
```

```{r}
MS_sim_msd[1:10,1:10]
```

## Calculating the Predictions for the Users

```{r}
# Calculate the predictions for user 1

# Initiate the prediction matrix and find the columns we need to predict for user 1.
pred_mat        <- MS_UI
cols_to_predict <- which(MS_UI[1, ] == 0)
num_cols        <- length(cols_to_predict)
```

```{r}
# Transform the UI matrix into a deviation matrix since we want to calculate weighted averages of the deviations
neighb_weights <- MS_sim[1, ]
row_avgs       <- apply(MS_UI, 1, mean, na.rm = TRUE)
dev_mat        <- MS_UI - matrix(rep(row_avgs, ncol(MS_UI)), ncol = ncol(MS_UI))
```

```{r}
dim(dev_mat)
dev_mat[1:10,1:10]
```

```{r}
# We'll calculate the predictions in two ways:

# First by looping over items where we want to make predictions


for (i in 1:num_cols) {
  
  # For each column to predict, first find all deviations for that item
  neighb_devs <- dev_mat[ ,cols_to_predict[i]]
  
  # For each column to predict, calculate the prediction as the weighted average
  pred_mat[1, cols_to_predict[i]] <- row_avgs[1] +  sum(neighb_devs * neighb_weights, na.rm = TRUE)/sum(neighb_weights, na.rm = TRUE)
}

```

```{r}
# Now using matrix equations

pred_mat2 <- MS_UI

weight_mat  <- matrix(rep(neighb_weights, ncol(MS_UI)), ncol = ncol(MS_UI))
weight_sub  <- weight_mat[, cols_to_predict]
neighb_devs <- dev_mat[ ,cols_to_predict]
```

```{r}
# Now fill in all of row 1 with matrix equations
pred_mat2[1, cols_to_predict] <- row_avgs[1] +  apply(neighb_devs * weight_sub, 2, sum, na.rm = TRUE)/sum(neighb_weights, na.rm = TRUE)


# They're the same
all(pred_mat2[1,] == pred_mat[1, ])
```

```{r}
# Calculate predictions for MS
# This calculation took me 15 minutes

MS_pred_pearson <- pred_matrix(MS_UI, MS_sim_pearson)
save(MS_pred_pearson, file = "MS_pred_pearson.RData")
```

```{r}
MS_pred_pearson[1:10,1:10]
```

```{r}
# Calculate predictions for movies
# This calculation took me 2493 second

movie_pred_pearson <- pred_matrix(movie_UI, movie_sim_pearson)
save(movie_pred_pearson, file = "movie_pred_pearson.RData")
```

```{r}
movie_pred[1:10,1:10]
```


